-- ============================================================
-- STUDENT ATTENDANCE SYSTEM — MySQL schema
-- ============================================================
-- How to run:
--   1. CREATE DATABASE attendance_db;
--   2. Open this file in MySQL Workbench, select attendance_db
--      in the schema dropdown, then Run (lightning icon)
--
-- Tables:
--   users      → admin + teacher logins (passwords = bcrypt hashes)
--   students   → roll no, name, class (FY-BCA / SY-BCA / TY-BCA)
--   subjects   → subject code + name + optional assigned teacher
--   attendance → one row per student per subject per date (P/A)
--
-- Key constraints (frequently asked in viva):
--   * UNIQUE(student_id, subject_id, date)
--       → a student can be marked only ONCE per subject per day
--   * ON DELETE CASCADE
--       → deleting a student/subject removes its attendance rows
--   * ON DELETE SET NULL
--       → deleting a teacher keeps the subject, teacher_id = NULL
-- ============================================================
CREATE DATABASE IF NOT EXISTS attendance_db;
USE attendance_db;

-- Users table holds BOTH roles: 'admin' and 'teacher'
-- password_hash = bcrypt hash generated by seed.js / routes/teachers.js
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','teacher') NOT NULL DEFAULT 'teacher',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  roll_no VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  class_name VARCHAR(50) NOT NULL DEFAULT 'FY-BCA',
  email VARCHAR(150) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subjects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  teacher_id INT NULL,
  FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL
);

-- One row per attendance mark.
-- The UNIQUE key is the heart of the system:
-- re-saving the same day triggers ON DUPLICATE KEY UPDATE
-- (see routes/attendance.js → POST /mark)
CREATE TABLE IF NOT EXISTS attendance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  subject_id INT NOT NULL,
  date DATE NOT NULL,
  status ENUM('Present','Absent') NOT NULL DEFAULT 'Present',
  marked_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_att (student_id, subject_id, date),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  FOREIGN KEY (marked_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Demo subjects (teacher assigned later from UI)
INSERT INTO subjects (code, name) VALUES
('CS101','Programming in C'),
('CS102','Web Technologies'),
('CS103','DBMS')
ON DUPLICATE KEY UPDATE name=VALUES(name);
